# Generated by Django 4.1.4 on 2022-12-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Django_hour', models.IntegerField()),
                ('Flusk_hour', models.IntegerField()),
                ('Pygame_hour', models.IntegerField()),
                ('CSS_html_hour', models.IntegerField()),
                ('PyQt5_hour', models.IntegerField()),
                ('Some_new_hour', models.IntegerField()),
            ],
        ),
    ]
