# Generated by Django 4.1.4 on 2022-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='hours',
            name='CSS_html_hour',
        ),
        migrations.AddField(
            model_name='hours',
            name='Git_Linux_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='Django_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='Flusk_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='PyQt5_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='Pygame_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hours',
            name='Some_new_hour',
            field=models.IntegerField(default=0),
        ),
    ]
