# Generated by Django 4.1.4 on 2022-12-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes_remove_hours_css_html_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='data',
            new_name='data_django',
        ),
        migrations.AddField(
            model_name='notes',
            name='data_flask',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='data_git_linux',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='data_new',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='data_pygame',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='data_pyqt5',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
